# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    webservice_user_provider:
        class: WebserviceUserBundle\Security\User\WebserviceUserProvider

    #custom openstack keystone authenticator
    webserviceuser_authenticator:
        class:     WebserviceUserBundle\Security\WebserviceUserAuthenticator
        arguments: ["@security.password_encoder"]
        
    curl_service:
        class: AppBundle\Services\CurlService