services:
#    webservice_user.example:
#        class: WebserviceUserBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    
    webservice_user_provider:
        class: WebserviceUserBundle\Security\User\WebserviceUserProvider
