# src/AppBundle/Resources/config/routing.yml
random:
    path:     /random/{limit}
    defaults: { _controller: AppBundle:Random:index }
    
vtn:
    path:   /vtn
    defaults: { _controller: AppBundle:Vtn:getVtn }